<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;


class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $sourcePath = public_path('frontend/img/cars/');
        $destinationPath = 'public/cars/images/';

        $cars = [
            [
                'id' => '1',
                'nama_mobil' => 'Suzuki Ertiga',
                'plat_nomor'  => 'H 28 YT',
                'slug' => 'suzuki-ertiga',
                'type_id' => '1',
                'price' => '300000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Mobil MPV yang ideal untuk keluarga dengan desain yang modern dan efisien.',
                'image1' => 'mpv-suzuki-ertiga-1.png',
                'image2' => 'mpv-suzuki-ertiga-2.png',
                'image3' => 'mpv-suzuki-ertiga-3.png',
                'image4' => 'mpv-suzuki-ertiga-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2',
                'nama_mobil' => 'Toyota Calya',
                'plat_nomor'  => 'H 29 YT',
                'slug' => 'toyota-calya',
                'type_id' => '1',
                'price' => '300000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'MPV kompak dengan desain yang stylish dan efisiensi bahan bakar yang baik.',
                'image1' => 'mpv-toyota-calya-1.png',
                'image2' => 'mpv-toyota-calya-2.png',
                'image3' => 'mpv-toyota-calya-3.png',
                'image4' => 'mpv-toyota-calya-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3',
                'nama_mobil' => 'Toyota Innova',
                'plat_nomor'  => 'H 30 YT',
                'slug' => 'toyota-innova',
                'type_id' => '1',
                'price' => '900000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'MPV yang luas dan nyaman, cocok untuk keluarga besar atau perjalanan jarak jauh.',
                'image1' => 'mpv-toyota-innova-1-hitam.png',
                'image2' => 'mpv-toyota-innova-2-hitam.png',
                'image3' => 'mpv-toyota-innova-3-hitam.png',
                'image4' => 'mpv-toyota-innova-4-hitam.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '4',
                'nama_mobil' => 'Toyota Innova',
                'plat_nomor'  => 'H 31 YT',
                'slug' => 'toyota-innova',
                'type_id' => '1',
                'price' => '1100000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Varian warna lain dari Toyota Innova yang menawarkan ruang yang luas dan kenyamanan maksimal.',
                'image1' => 'mpv-toyota-innova-1-putih.png',
                'image2' => 'mpv-toyota-innova-2-putih.png',
                'image3' => 'mpv-toyota-innova-3-putih.png',
                'image4' => 'mpv-toyota-innova-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5',
                'nama_mobil' => 'Toyota Venturer',
                'plat_nomor'  => 'H 32 YT',
                'slug' => 'toyota-venturer',
                'type_id' => '1',
                'price' => '700000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'SUV dengan desain sporty yang cocok untuk petualangan dan gaya hidup aktif.',
                'image1' => 'mpv-toyota-venturer-1-abu.png',
                'image2' => 'mpv-toyota-venturer-2-abu.png',
                'image3' => 'mpv-toyota-venturer-3-abu.png',
                'image4' => 'mpv-toyota-venturer-4-abu.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6',
                'nama_mobil' => 'Toyota Venturer',
                'plat_nomor'  => 'H 33 YT',
                'slug' => 'toyota-venturer',
                'type_id' => '1',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Varian warna lain dari Toyota Venturer yang memberikan kombinasi gaya dan kenyamanan.',
                'image1' => 'mpv-toyota-venturer-1-putih.png',
                'image2' => 'mpv-toyota-venturer-2-putih.png',
                'image3' => 'mpv-toyota-venturer-3-putih.png',
                'image4' => 'mpv-toyota-venturer-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7',
                'nama_mobil' => 'Daihatsu Terios',
                'plat_nomor'  => 'H 34 YT',
                'slug' => 'daihatsu-terios',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'SUV kompak yang tangguh dan handal di berbagai medan.',
                'image1' => 'suv-daihatsu-terios-1.png',
                'image2' => 'suv-daihatsu-terios-2.png',
                'image3' => 'suv-daihatsu-terios-3.png',
                'image4' => 'suv-daihatsu-terios-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8',
                'nama_mobil' => 'Honda BRV',
                'plat_nomor'  => 'H 35 YT',
                'slug' => 'honda-brv',
                'type_id' => '2',
                'price' => '800000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'SUV yang elegan dengan ruang kabin luas, cocok untuk perjalanan keluarga atau bersama teman.',
                'image1' => 'suv-honda-brv-1-hitam.png',
                'image2' => 'suv-honda-brv-2-hitam.png',
                'image3' => 'suv-honda-brv-3-hitam.png',
                'image4' => 'suv-honda-brv-4-hitam.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '9',
                'nama_mobil' => 'Honda BRV',
                'plat_nomor'  => 'H 36 YT',
                'slug' => 'honda-brv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Varian warna lain dari Honda BRV yang menawarkan gaya dan kenyamanan.',
                'image1' => 'suv-honda-brv-1-putih.png',
                'image2' => 'suv-honda-brv-2-putih.png',
                'image3' => 'suv-honda-brv-3-putih.png',
                'image4' => 'suv-honda-brv-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '10',
                'nama_mobil' => 'Honda CRV',
                'plat_nomor'  => 'H 37 YT',
                'slug' => 'honda-crv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'SUV premium dengan desain elegan dan fitur canggih untuk kenyamanan maksimal.',
                'image1' => 'suv-honda-crv-1.png',
                'image2' => 'suv-honda-crv-2.png',
                'image3' => 'suv-honda-crv-3.png',
                'image4' => 'suv-honda-crv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '11',
                'nama_mobil' => 'Honda HRV',
                'plat_nomor'  => 'H 38 YT',
                'slug' => 'honda-hrv',
                'type_id' => '2',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'SUV kompak dengan gaya yang dinamis dan efisiensi bahan bakar yang baik.',
                'image1' => 'suv-honda-hrv-1.png',
                'image2' => 'suv-honda-hrv-2.png',
                'image3' => 'suv-honda-hrv-3.png',
                'image4' => 'suv-honda-hrv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '12',
                'nama_mobil' => 'Honda WRV',
                'plat_nomor'  => 'H 39 YT',
                'slug' => 'honda-wrv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'SUV modern yang cocok untuk kehidupan perkotaan dengan kenyamanan dan keamanan yang prima.',
                'image1' => 'suv-honda-wrv-1.png',
                'image2' => 'suv-honda-wrv-2.png',
                'image3' => 'suv-honda-wrv-3.png',
                'image4' => 'suv-honda-wrv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '13',
                'nama_mobil' => 'Honda CRV',
                'plat_nomor'  => 'H 40 YT',
                'slug' => 'honda-crv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'SUV premium dengan desain elegan dan fitur canggih untuk kenyamanan maksimal.',
                'image1' => 'suv-honda-crv-1.png',
                'image2' => 'suv-honda-crv-2.png',
                'image3' => 'suv-honda-crv-3.png',
                'image4' => 'suv-honda-crv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '14',
                'nama_mobil' => 'Mitsubishi Xpander',
                'plat_nomor'  => 'H 41 YT',
                'slug' => 'mitsubishi-xpander',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'MPV dengan desain futuristik dan ruang kabin yang luas, ideal untuk perjalanan keluarga.',
                'image1' => 'suv-mitsubishi-xpander-1.png',
                'image2' => 'suv-mitsubishi-xpander-2.png',
                'image3' => 'suv-mitsubishi-xpander-3.png',
                'image4' => 'suv-mitsubishi-xpander-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '15',
                'nama_mobil' => 'Toyota Fortuner',
                'plat_nomor'  => 'H 42 YT',
                'slug' => 'toyota-fortuner',
                'type_id' => '2',
                'price' => '1400000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'SUV yang kuat dan tangguh, cocok untuk petualangan di segala medan.',
                'image1' => 'suv-toyota-fortuner-1.png',
                'image2' => 'suv-toyota-fortuner-2.png',
                'image3' => 'suv-toyota-fortuner-3.png',
                'image4' => 'suv-toyota-fortuner-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '16',
                'nama_mobil' => 'Honda Jazz',
                'plat_nomor'  => 'H 43 YT',
                'slug' => 'honda-jazz',
                'type_id' => '3',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Hatchback yang energik dengan ruang kabin yang fleksibel dan efisiensi bahan bakar yang baik.',
                'image1' => 'hatchback-honda-jazz-1.png',
                'image2' => 'hatchback-honda-jazz-2.png',
                'image3' => 'hatchback-honda-jazz-3.png',
                'image4' => 'hatchback-honda-jazz-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '17',
                'nama_mobil' => 'Honda Accord',
                'plat_nomor'  => 'H 44 YT',
                'slug' => 'honda-accord',
                'type_id' => '4',
                'price' => '1000000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Sedan premium dengan performa tinggi dan desain yang elegan, cocok untuk gaya hidup profesional.',
                'image1' => 'sedan-honda-accord-1.png',
                'image2' => 'sedan-honda-accord-2.png',
                'image3' => 'sedan-honda-accord-3.png',
                'image4' => 'sedan-honda-accord-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '18',
                'nama_mobil' => 'Honda City',
                'plat_nomor'  => 'H 45 YT',
                'slug' => 'honda-city',
                'type_id' => '4',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Sedan kompak yang menggabungkan kenyamanan dan kepraktisan dalam satu paket.',
                'image1' => 'sedan-honda-city-1.png',
                'image2' => 'sedan-honda-city-2.png',
                'image3' => 'sedan-honda-city-3.png',
                'image4' => 'sedan-honda-city-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '19',
                'nama_mobil' => 'Toyota Camry',
                'plat_nomor'  => 'H 46 YT',
                'slug' => 'toyota-camry',
                'type_id' => '4',
                'price' => '700000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Sedan mewah dengan teknologi canggih dan kenyamanan premium untuk pengalaman berkendara yang istimewa.',
                'image1' => 'sedan-toyota-camry-1.png',
                'image2' => 'sedan-toyota-camry-2.png',
                'image3' => 'sedan-toyota-camry-3.png',
                'image4' => 'sedan-toyota-camry-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];


        foreach ($cars as $car) {
            // Iterate over each image
            for ($i = 1; $i <= 4; $i++) {
                $imageKey = 'image' . $i;

                // Get source and destination paths for the current image
                $sourceFile = $sourcePath . $car[$imageKey];
                $destinationFile = $destinationPath . basename($car[$imageKey]); // Ambil bagian akhir jalur gambar

                // Check if the destination file doesn't exist
                if (!Storage::exists($destinationFile)) {
                    // Copy the image to the destination path
                    Storage::put($destinationFile, file_get_contents($sourceFile));
                }

                // Update the photo path to the storage path for the current image
                $car[$imageKey] = 'cars/images/' . basename($car[$imageKey]);
            }

            // Create the car record
            Car::create($car);
        }
    }
}
